const base = {
  newProject:'＋ Nouveau projet', workspace:'ESPACE DE TRAVAIL', home:'Accueil', projects:'Projets', templates:'Modèles', settings:'Paramètres', connected:'IA connectée', ws:'Espace de travail', app:'Mon application', launch:'▶ Lancer', eyebrow:'✦ CRÉATEUR D’APPS IA', title:'Crée ton application', title2:'avec l’IA.', subtitle:'Décris ton idée, importe ton projet et laisse CODE2IA construire avec toi.', assistant:'Assistant IA', ready:'Qwen · Prêt', hello:'Salut 👋 Que veux-tu créer aujourd’hui ?', userExample:'Je veux créer une application moderne.', answer:'Parfait. Je peux générer la structure, analyser tes fichiers et préparer ton projet.', prompt:'Décris ton application...', attach:'↗ Joindre un fichier', preview:'Aperçu', live:'Aperçu en direct', start:'Commencer', powered:'✦ PROPULSÉ PAR CODE2IA', mockTitle:'Construis|quelque chose|d’incroyable.', mockText:'Ton application générée par l’IA apparaît ici en temps réel.', explore:'Explorer →', files:'Fichiers du projet', fileCount:'3 fichiers', analysis:'Analyse IA', language:'Langue', project:'Projet', state:'État', webApp:'Application web', noProblem:'✓ Aucun problème'
};

const translations = {
  fr: base,
  en: {newProject:'＋ New project',workspace:'WORKSPACE',home:'Home',projects:'Projects',templates:'Templates',settings:'Settings',connected:'AI connected',ws:'Workspace',app:'My application',launch:'▶ Run',eyebrow:'✦ AI APP BUILDER',title:'Create your application',title2:'with AI.',subtitle:'Describe your idea, import your project and let CODE2IA build with you.',assistant:'AI Assistant',ready:'Qwen · Ready',hello:'Hi 👋 What do you want to create today?',userExample:'I want to create a modern application.',answer:'Perfect. I can generate the structure, analyze your files and prepare your project.',prompt:'Describe your application...',attach:'↗ Attach a file',preview:'Preview',live:'Live preview',start:'Get started',powered:'✦ POWERED BY CODE2IA',mockTitle:'Build|something|incredible.',mockText:'Your AI-generated application appears here in real time.',explore:'Explore →',files:'Project files',fileCount:'3 files',analysis:'AI analysis',language:'Language',project:'Project',state:'Status',webApp:'Web Application',noProblem:'✓ No issues'},
  es: {newProject:'＋ Nuevo proyecto',workspace:'ESPACIO DE TRABAJO',home:'Inicio',projects:'Proyectos',templates:'Plantillas',settings:'Configuración',connected:'IA conectada',ws:'Espacio de trabajo',app:'Mi aplicación',launch:'▶ Ejecutar',eyebrow:'✦ CREADOR DE APPS CON IA',title:'Crea tu aplicación',title2:'con IA.',subtitle:'Describe tu idea, importa tu proyecto y deja que CODE2IA construya contigo.',assistant:'Asistente IA',ready:'Qwen · Listo',hello:'Hola 👋 ¿Qué quieres crear hoy?',userExample:'Quiero crear una aplicación moderna.',answer:'Perfecto. Puedo generar la estructura, analizar tus archivos y preparar tu proyecto.',prompt:'Describe tu aplicación...',attach:'↗ Adjuntar un archivo',preview:'Vista previa',live:'Vista previa en vivo',start:'Comenzar',powered:'✦ IMPULSADO POR CODE2IA',mockTitle:'Construye|algo|increíble.',mockText:'Tu aplicación generada por IA aparece aquí en tiempo real.',explore:'Explorar →',files:'Archivos del proyecto',fileCount:'3 archivos',analysis:'Análisis IA',language:'Idioma',project:'Proyecto',state:'Estado',webApp:'Aplicación web',noProblem:'✓ Ningún problema'},
  de: {newProject:'＋ Neues Projekt',workspace:'ARBEITSBEREICH',home:'Startseite',projects:'Projekte',templates:'Vorlagen',settings:'Einstellungen',connected:'KI verbunden',ws:'Arbeitsbereich',app:'Meine Anwendung',launch:'▶ Starten',eyebrow:'✦ KI-APP-BUILDER',title:'Erstelle deine Anwendung',title2:'mit KI.',subtitle:'Beschreibe deine Idee, importiere dein Projekt und lass CODE2IA mit dir bauen.',assistant:'KI-Assistent',ready:'Qwen · Bereit',hello:'Hallo 👋 Was möchtest du heute erstellen?',userExample:'Ich möchte eine moderne Anwendung erstellen.',answer:'Perfekt. Ich kann die Struktur erstellen, deine Dateien analysieren und dein Projekt vorbereiten.',prompt:'Beschreibe deine Anwendung...',attach:'↗ Datei anhängen',preview:'Vorschau',live:'Live-Vorschau',start:'Loslegen',powered:'✦ POWERED BY CODE2IA',mockTitle:'Baue|etwas|Unglaubliches.',mockText:'Deine von KI erstellte Anwendung erscheint hier in Echtzeit.',explore:'Entdecken →',files:'Projektdateien',fileCount:'3 Dateien',analysis:'KI-Analyse',language:'Sprache',project:'Projekt',state:'Status',webApp:'Webanwendung',noProblem:'✓ Keine Probleme'},
  it: {newProject:'＋ Nuovo progetto',workspace:'AREA DI LAVORO',home:'Home',projects:'Progetti',templates:'Modelli',settings:'Impostazioni',connected:'IA connessa',ws:'Area di lavoro',app:'La mia applicazione',launch:'▶ Avvia',eyebrow:'✦ CREATORE DI APP IA',title:'Crea la tua applicazione',title2:'con l’IA.',subtitle:'Descrivi la tua idea, importa il progetto e lascia che CODE2IA costruisca con te.',assistant:'Assistente IA',ready:'Qwen · Pronto',hello:'Ciao 👋 Cosa vuoi creare oggi?',userExample:'Voglio creare un’applicazione moderna.',answer:'Perfetto. Posso generare la struttura, analizzare i tuoi file e preparare il progetto.',prompt:'Descrivi la tua applicazione...',attach:'↗ Allega un file',preview:'Anteprima',live:'Anteprima live',start:'Inizia',powered:'✦ POWERED BY CODE2IA',mockTitle:'Costruisci|qualcosa|di incredibile.',mockText:'La tua applicazione generata dall’IA appare qui in tempo reale.',explore:'Esplora →',files:'File del progetto',fileCount:'3 file',analysis:'Analisi IA',language:'Lingua',project:'Progetto',state:'Stato',webApp:'Applicazione web',noProblem:'✓ Nessun problema'},
  pt: {newProject:'＋ Novo projeto',workspace:'ÁREA DE TRABALHO',home:'Início',projects:'Projetos',templates:'Modelos',settings:'Configurações',connected:'IA conectada',ws:'Área de trabalho',app:'Minha aplicação',launch:'▶ Executar',eyebrow:'✦ CRIADOR DE APPS COM IA',title:'Crie sua aplicação',title2:'com IA.',subtitle:'Descreva sua ideia, importe seu projeto e deixe a CODE2IA construir com você.',assistant:'Assistente IA',ready:'Qwen · Pronto',hello:'Olá 👋 O que você quer criar hoje?',userExample:'Quero criar uma aplicação moderna.',answer:'Perfeito. Posso gerar a estrutura, analisar seus arquivos e preparar seu projeto.',prompt:'Descreva sua aplicação...',attach:'↗ Anexar um arquivo',preview:'Pré-visualização',live:'Pré-visualização ao vivo',start:'Começar',powered:'✦ DESENVOLVIDO COM CODE2IA',mockTitle:'Construa|algo|incrível.',mockText:'Sua aplicação gerada por IA aparece aqui em tempo real.',explore:'Explorar →',files:'Arquivos do projeto',fileCount:'3 arquivos',analysis:'Análise IA',language:'Idioma',project:'Projeto',state:'Estado',webApp:'Aplicação web',noProblem:'✓ Nenhum problema'},
  ar: {newProject:'＋ مشروع جديد',workspace:'مساحة العمل',home:'الرئيسية',projects:'المشاريع',templates:'القوالب',settings:'الإعدادات',connected:'الذكاء الاصطناعي متصل',ws:'مساحة العمل',app:'تطبيقي',launch:'▶ تشغيل',eyebrow:'✦ منشئ التطبيقات بالذكاء الاصطناعي',title:'أنشئ تطبيقك',title2:'بالذكاء الاصطناعي.',subtitle:'صف فكرتك واستورد مشروعك ودع CODE2IA تبنيه معك.',assistant:'مساعد الذكاء الاصطناعي',ready:'Qwen · جاهز',hello:'مرحبًا 👋 ماذا تريد أن تنشئ اليوم؟',userExample:'أريد إنشاء تطبيق حديث.',answer:'رائع. يمكنني إنشاء البنية وتحليل ملفاتك وتجهيز مشروعك.',prompt:'صف تطبيقك...',attach:'↗ إرفاق ملف',preview:'معاينة',live:'معاينة مباشرة',start:'ابدأ',powered:'✦ مدعوم بواسطة CODE2IA',mockTitle:'ابنِ|شيئًا|رائعًا.',mockText:'سيظهر تطبيقك المُنشأ بالذكاء الاصطناعي هنا في الوقت الفعلي.',explore:'استكشف ←',files:'ملفات المشروع',fileCount:'3 ملفات',analysis:'تحليل الذكاء الاصطناعي',language:'اللغة',project:'المشروع',state:'الحالة',webApp:'تطبيق ويب',noProblem:'✓ لا توجد مشاكل'},
  zh: {newProject:'＋ 新建项目',workspace:'工作区',home:'首页',projects:'项目',templates:'模板',settings:'设置',connected:'AI 已连接',ws:'工作区',app:'我的应用',launch:'▶ 运行',eyebrow:'✦ AI 应用构建器',title:'创建你的应用',title2:'使用 AI。',subtitle:'描述你的想法，导入项目，让 CODE2IA 与你一起构建。',assistant:'AI 助手',ready:'Qwen · 就绪',hello:'你好 👋 今天想创建什么？',userExample:'我想创建一个现代应用。',answer:'很好。我可以生成结构、分析文件并准备项目。',prompt:'描述你的应用...',attach:'↗ 附加文件',preview:'预览',live:'实时预览',start:'开始',powered:'✦ CODE2IA 驱动',mockTitle:'构建|一些|精彩的东西。',mockText:'你的 AI 生成应用会实时显示在这里。',explore:'探索 →',files:'项目文件',fileCount:'3 个文件',analysis:'AI 分析',language:'语言',project:'项目',state:'状态',webApp:'Web 应用',noProblem:'✓ 没有问题'},
  ja: {newProject:'＋ 新しいプロジェクト',workspace:'ワークスペース',home:'ホーム',projects:'プロジェクト',templates:'テンプレート',settings:'設定',connected:'AI 接続済み',ws:'ワークスペース',app:'マイアプリ',launch:'▶ 実行',eyebrow:'✦ AI アプリビルダー',title:'アプリを作成',title2:'AI と一緒に。',subtitle:'アイデアを説明し、プロジェクトを読み込んで、CODE2IA と一緒に構築しましょう。',assistant:'AI アシスタント',ready:'Qwen · 準備完了',hello:'こんにちは 👋 今日は何を作りますか？',userExample:'モダンなアプリを作りたいです。',answer:'完璧です。構造の生成、ファイル分析、プロジェクトの準備ができます。',prompt:'アプリを説明してください...',attach:'↗ ファイルを添付',preview:'プレビュー',live:'ライブプレビュー',start:'始める',powered:'✦ CODE2IA が提供',mockTitle:'何か|素晴らしいものを|作ろう。',mockText:'AI が生成したアプリがリアルタイムでここに表示されます。',explore:'探索 →',files:'プロジェクトファイル',fileCount:'3 ファイル',analysis:'AI 分析',language:'言語',project:'プロジェクト',state:'状態',webApp:'Web アプリケーション',noProblem:'✓ 問題ありません'},
  ko: {newProject:'＋ 새 프로젝트',workspace:'워크스페이스',home:'홈',projects:'프로젝트',templates:'템플릿',settings:'설정',connected:'AI 연결됨',ws:'워크스페이스',app:'내 애플리케이션',launch:'▶ 실행',eyebrow:'✦ AI 앱 빌더',title:'애플리케이션 만들기',title2:'AI와 함께.',subtitle:'아이디어를 설명하고 프로젝트를 가져와 CODE2IA와 함께 만들어 보세요.',assistant:'AI 어시스턴트',ready:'Qwen · 준비됨',hello:'안녕하세요 👋 오늘 무엇을 만들까요?',userExample:'현대적인 애플리케이션을 만들고 싶어요.',answer:'좋습니다. 구조를 생성하고 파일을 분석하고 프로젝트를 준비할 수 있습니다.',prompt:'애플리케이션을 설명하세요...',attach:'↗ 파일 첨부',preview:'미리보기',live:'실시간 미리보기',start:'시작하기',powered:'✦ CODE2IA 제공',mockTitle:'무언가|멋진 것을|만들어 보세요.',mockText:'AI가 생성한 애플리케이션이 여기에 실시간으로 표시됩니다.',explore:'탐색 →',files:'프로젝트 파일',fileCount:'파일 3개',analysis:'AI 분석',language:'언어',project:'프로젝트',state:'상태',webApp:'웹 애플리케이션',noProblem:'✓ 문제 없음'}
};

const languageNames = {fr:'Français',en:'English',es:'Español',de:'Deutsch',it:'Italiano',pt:'Português',ar:'العربية',zh:'中文',ja:'日本語',ko:'한국어'};

function setLanguage(lang) {
  const t = translations[lang] || translations.fr;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el => { const key = el.dataset.i18n; if (t[key]) el.textContent = t[key]; });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { const key = el.dataset.i18nPlaceholder; if (t[key]) el.placeholder = t[key]; });
  const title = document.querySelector('[data-i18n-title]');
  if (title && t.title) title.innerHTML = `${t.title}<br><span>${t.title2 || ''}</span>`;
  const mockTitle = document.querySelector('[data-i18n-mock-title]');
  if (mockTitle && t.mockTitle) mockTitle.innerHTML = t.mockTitle.split('|').map((x,i)=>i===2?`<em>${x}</em>`:x).join('<br>');
  localStorage.setItem('code2ia-language', lang);
  const select = document.getElementById('language-select');
  if (select) select.value = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  const select = document.getElementById('language-select');
  if (select) {
    select.innerHTML = Object.entries(languageNames).map(([code,name]) => `<option value="${code}">${name}</option>`).join('');
    select.addEventListener('change', e => setLanguage(e.target.value));
  }
  setLanguage(localStorage.getItem('code2ia-language') || 'fr');
});
